# Build arguments
ARG SOURCE_CODE=.

FROM registry.access.redhat.com/ubi9/go-toolset:1.22@sha256:703937e152d049e62f5aa8ab274a4253468ab70f7b790d92714b37cf0a140555 as builder

## Build args to be used at this step
ARG SOURCE_CODE
 
USER root
 
WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

# Copy the go source
COPY . .
 
RUN CGO_ENABLED=1 GOOS=linux GOEXPERIMENT=strictfipsruntime go build -tags strictfipsruntime -a -o model-registry main.go
 
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:14f14e03d68f7fd5f2b18a13478b6b127c341b346c86b6e0b886ed2b7573b8e0
 
WORKDIR /
 
COPY --from=builder /workspace/model-registry .
 
RUN chmod +x /model-registry
 
USER root
 
USER 1001
 
# Expose default proxy port
EXPOSE 8080
 
# Start the model registry proxy
CMD /model-registry proxy -logtostderr=true
 
LABEL com.redhat.component="odh-model-registry-container" \
      name="managed-open-data-hub/odh-model-registry-rhel8" \
      description="Container that provides a central repository for model developers to store and manage models, versions, and artifacts metadata." \
      summary="odh-model-registry" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-model-registry" \
      io.k8s.description="odh-model-registry" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
